version: '3.4'
services:
  db:
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: Admin357/
      MYSQL_USER: root
      MYSQL_PASSWORD: Admin357/
      MYSQL_DATABASE: blog_pessoal
    ports:
      - "3308:3306"
    networks:
      - generation-network
networks:
    generation-network:
        driver: bridge