version: "3.3"

services:
  db:
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: Admin357/
      MYSQL_USER: root
      MYSQL_PASSWORD: Admin357/
      MYSQL_DATABASE: blog_pessoal
    ports:
      - "3308:3306"
    networks:
      - udemy
  blog-spring:
    restart: always
    build: ./blogpessoal-api
    build: ./blogpessoal-api
    working_dir: /blogpessoal-api
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./blogpessoal-api:/blogpessoal-api
      - ~/.m2:/root/.m2
    ports:
      - "9000:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - udemy

networks:
    udemy:
        driver: bridge