version: "3.3"

services:
  db:
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build: ./src
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: Admin357/
      MYSQL_USER: root
      MYSQL_PASSWORD: Admin357/
      MYSQL_DATABASE: blog_pessoal
    ports:
      - "3308:3306"
    networks:
      - udemy
  server-admin:
    image: udemy-server-admin:v1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    links:
      - db
    depends_on:
      - db
    networks:
      - udemy

networks:
  udemy:
    external: true